version: '2.4'

services:
    express:
        build:
            target: dev
        ports:
            - 6789:6789
            - 9229:9229
        env_file:
            - .development.env
        volumes:
            - .:/node/app
            - /node/app/node_modules
